// Code generated by ent, DO NOT EDIT.

package idempotencykey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/devgugga/galaxy-pay/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLTE(FieldID, id))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldKey, v))
}

// PaymentID applies equality check predicate on the "payment_id" field. It's identical to PaymentIDEQ.
func PaymentID(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldPaymentID, v))
}

// StatusCode applies equality check predicate on the "status_code" field. It's identical to StatusCodeEQ.
func StatusCode(v int) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldStatusCode, v))
}

// RequestHash applies equality check predicate on the "request_hash" field. It's identical to RequestHashEQ.
func RequestHash(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldRequestHash, v))
}

// ResponseBody applies equality check predicate on the "response_body" field. It's identical to ResponseBodyEQ.
func ResponseBody(v []byte) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldResponseBody, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldCreatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldExpiresAt, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldContainsFold(FieldKey, v))
}

// PaymentIDEQ applies the EQ predicate on the "payment_id" field.
func PaymentIDEQ(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldPaymentID, v))
}

// PaymentIDNEQ applies the NEQ predicate on the "payment_id" field.
func PaymentIDNEQ(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNEQ(FieldPaymentID, v))
}

// PaymentIDIn applies the In predicate on the "payment_id" field.
func PaymentIDIn(vs ...string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldIn(FieldPaymentID, vs...))
}

// PaymentIDNotIn applies the NotIn predicate on the "payment_id" field.
func PaymentIDNotIn(vs ...string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNotIn(FieldPaymentID, vs...))
}

// PaymentIDGT applies the GT predicate on the "payment_id" field.
func PaymentIDGT(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGT(FieldPaymentID, v))
}

// PaymentIDGTE applies the GTE predicate on the "payment_id" field.
func PaymentIDGTE(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGTE(FieldPaymentID, v))
}

// PaymentIDLT applies the LT predicate on the "payment_id" field.
func PaymentIDLT(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLT(FieldPaymentID, v))
}

// PaymentIDLTE applies the LTE predicate on the "payment_id" field.
func PaymentIDLTE(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLTE(FieldPaymentID, v))
}

// PaymentIDContains applies the Contains predicate on the "payment_id" field.
func PaymentIDContains(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldContains(FieldPaymentID, v))
}

// PaymentIDHasPrefix applies the HasPrefix predicate on the "payment_id" field.
func PaymentIDHasPrefix(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldHasPrefix(FieldPaymentID, v))
}

// PaymentIDHasSuffix applies the HasSuffix predicate on the "payment_id" field.
func PaymentIDHasSuffix(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldHasSuffix(FieldPaymentID, v))
}

// PaymentIDIsNil applies the IsNil predicate on the "payment_id" field.
func PaymentIDIsNil() predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldIsNull(FieldPaymentID))
}

// PaymentIDNotNil applies the NotNil predicate on the "payment_id" field.
func PaymentIDNotNil() predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNotNull(FieldPaymentID))
}

// PaymentIDEqualFold applies the EqualFold predicate on the "payment_id" field.
func PaymentIDEqualFold(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEqualFold(FieldPaymentID, v))
}

// PaymentIDContainsFold applies the ContainsFold predicate on the "payment_id" field.
func PaymentIDContainsFold(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldContainsFold(FieldPaymentID, v))
}

// StatusCodeEQ applies the EQ predicate on the "status_code" field.
func StatusCodeEQ(v int) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldStatusCode, v))
}

// StatusCodeNEQ applies the NEQ predicate on the "status_code" field.
func StatusCodeNEQ(v int) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNEQ(FieldStatusCode, v))
}

// StatusCodeIn applies the In predicate on the "status_code" field.
func StatusCodeIn(vs ...int) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldIn(FieldStatusCode, vs...))
}

// StatusCodeNotIn applies the NotIn predicate on the "status_code" field.
func StatusCodeNotIn(vs ...int) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNotIn(FieldStatusCode, vs...))
}

// StatusCodeGT applies the GT predicate on the "status_code" field.
func StatusCodeGT(v int) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGT(FieldStatusCode, v))
}

// StatusCodeGTE applies the GTE predicate on the "status_code" field.
func StatusCodeGTE(v int) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGTE(FieldStatusCode, v))
}

// StatusCodeLT applies the LT predicate on the "status_code" field.
func StatusCodeLT(v int) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLT(FieldStatusCode, v))
}

// StatusCodeLTE applies the LTE predicate on the "status_code" field.
func StatusCodeLTE(v int) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLTE(FieldStatusCode, v))
}

// RequestHashEQ applies the EQ predicate on the "request_hash" field.
func RequestHashEQ(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldRequestHash, v))
}

// RequestHashNEQ applies the NEQ predicate on the "request_hash" field.
func RequestHashNEQ(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNEQ(FieldRequestHash, v))
}

// RequestHashIn applies the In predicate on the "request_hash" field.
func RequestHashIn(vs ...string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldIn(FieldRequestHash, vs...))
}

// RequestHashNotIn applies the NotIn predicate on the "request_hash" field.
func RequestHashNotIn(vs ...string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNotIn(FieldRequestHash, vs...))
}

// RequestHashGT applies the GT predicate on the "request_hash" field.
func RequestHashGT(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGT(FieldRequestHash, v))
}

// RequestHashGTE applies the GTE predicate on the "request_hash" field.
func RequestHashGTE(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGTE(FieldRequestHash, v))
}

// RequestHashLT applies the LT predicate on the "request_hash" field.
func RequestHashLT(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLT(FieldRequestHash, v))
}

// RequestHashLTE applies the LTE predicate on the "request_hash" field.
func RequestHashLTE(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLTE(FieldRequestHash, v))
}

// RequestHashContains applies the Contains predicate on the "request_hash" field.
func RequestHashContains(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldContains(FieldRequestHash, v))
}

// RequestHashHasPrefix applies the HasPrefix predicate on the "request_hash" field.
func RequestHashHasPrefix(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldHasPrefix(FieldRequestHash, v))
}

// RequestHashHasSuffix applies the HasSuffix predicate on the "request_hash" field.
func RequestHashHasSuffix(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldHasSuffix(FieldRequestHash, v))
}

// RequestHashIsNil applies the IsNil predicate on the "request_hash" field.
func RequestHashIsNil() predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldIsNull(FieldRequestHash))
}

// RequestHashNotNil applies the NotNil predicate on the "request_hash" field.
func RequestHashNotNil() predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNotNull(FieldRequestHash))
}

// RequestHashEqualFold applies the EqualFold predicate on the "request_hash" field.
func RequestHashEqualFold(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEqualFold(FieldRequestHash, v))
}

// RequestHashContainsFold applies the ContainsFold predicate on the "request_hash" field.
func RequestHashContainsFold(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldContainsFold(FieldRequestHash, v))
}

// ResponseBodyEQ applies the EQ predicate on the "response_body" field.
func ResponseBodyEQ(v []byte) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldResponseBody, v))
}

// ResponseBodyNEQ applies the NEQ predicate on the "response_body" field.
func ResponseBodyNEQ(v []byte) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNEQ(FieldResponseBody, v))
}

// ResponseBodyIn applies the In predicate on the "response_body" field.
func ResponseBodyIn(vs ...[]byte) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldIn(FieldResponseBody, vs...))
}

// ResponseBodyNotIn applies the NotIn predicate on the "response_body" field.
func ResponseBodyNotIn(vs ...[]byte) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNotIn(FieldResponseBody, vs...))
}

// ResponseBodyGT applies the GT predicate on the "response_body" field.
func ResponseBodyGT(v []byte) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGT(FieldResponseBody, v))
}

// ResponseBodyGTE applies the GTE predicate on the "response_body" field.
func ResponseBodyGTE(v []byte) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGTE(FieldResponseBody, v))
}

// ResponseBodyLT applies the LT predicate on the "response_body" field.
func ResponseBodyLT(v []byte) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLT(FieldResponseBody, v))
}

// ResponseBodyLTE applies the LTE predicate on the "response_body" field.
func ResponseBodyLTE(v []byte) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLTE(FieldResponseBody, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLTE(FieldCreatedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLTE(FieldExpiresAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IdempotencyKey) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IdempotencyKey) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IdempotencyKey) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.NotPredicates(p))
}
