// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// IdempotencyKeysColumns holds the columns for the "idempotency_keys" table.
	IdempotencyKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "key", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "payment_id", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "status_code", Type: field.TypeInt, Default: 200},
		{Name: "request_hash", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "response_body", Type: field.TypeBytes},
		{Name: "response_headers", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
	}
	// IdempotencyKeysTable holds the schema information for the "idempotency_keys" table.
	IdempotencyKeysTable = &schema.Table{
		Name:       "idempotency_keys",
		Columns:    IdempotencyKeysColumns,
		PrimaryKey: []*schema.Column{IdempotencyKeysColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idempotencykey_key",
				Unique:  true,
				Columns: []*schema.Column{IdempotencyKeysColumns[1]},
			},
			{
				Name:    "idempotencykey_expires_at",
				Unique:  false,
				Columns: []*schema.Column{IdempotencyKeysColumns[8]},
			},
			{
				Name:    "idempotencykey_payment_id",
				Unique:  false,
				Columns: []*schema.Column{IdempotencyKeysColumns[2]},
			},
			{
				Name:    "idempotencykey_key_expires_at",
				Unique:  false,
				Columns: []*schema.Column{IdempotencyKeysColumns[1], IdempotencyKeysColumns[8]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		IdempotencyKeysTable,
	}
)

func init() {
}
