// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/devgugga/galaxy-pay/ent/idempotencykey"
	"github.com/devgugga/galaxy-pay/ent/predicate"
)

// IdempotencyKeyUpdate is the builder for updating IdempotencyKey entities.
type IdempotencyKeyUpdate struct {
	config
	hooks    []Hook
	mutation *IdempotencyKeyMutation
}

// Where appends a list predicates to the IdempotencyKeyUpdate builder.
func (_u *IdempotencyKeyUpdate) Where(ps ...predicate.IdempotencyKey) *IdempotencyKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *IdempotencyKeyUpdate) SetKey(v string) *IdempotencyKeyUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *IdempotencyKeyUpdate) SetNillableKey(v *string) *IdempotencyKeyUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetPaymentID sets the "payment_id" field.
func (_u *IdempotencyKeyUpdate) SetPaymentID(v string) *IdempotencyKeyUpdate {
	_u.mutation.SetPaymentID(v)
	return _u
}

// SetNillablePaymentID sets the "payment_id" field if the given value is not nil.
func (_u *IdempotencyKeyUpdate) SetNillablePaymentID(v *string) *IdempotencyKeyUpdate {
	if v != nil {
		_u.SetPaymentID(*v)
	}
	return _u
}

// ClearPaymentID clears the value of the "payment_id" field.
func (_u *IdempotencyKeyUpdate) ClearPaymentID() *IdempotencyKeyUpdate {
	_u.mutation.ClearPaymentID()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *IdempotencyKeyUpdate) SetStatusCode(v int) *IdempotencyKeyUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *IdempotencyKeyUpdate) SetNillableStatusCode(v *int) *IdempotencyKeyUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *IdempotencyKeyUpdate) AddStatusCode(v int) *IdempotencyKeyUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetRequestHash sets the "request_hash" field.
func (_u *IdempotencyKeyUpdate) SetRequestHash(v string) *IdempotencyKeyUpdate {
	_u.mutation.SetRequestHash(v)
	return _u
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (_u *IdempotencyKeyUpdate) SetNillableRequestHash(v *string) *IdempotencyKeyUpdate {
	if v != nil {
		_u.SetRequestHash(*v)
	}
	return _u
}

// ClearRequestHash clears the value of the "request_hash" field.
func (_u *IdempotencyKeyUpdate) ClearRequestHash() *IdempotencyKeyUpdate {
	_u.mutation.ClearRequestHash()
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *IdempotencyKeyUpdate) SetResponseBody(v []byte) *IdempotencyKeyUpdate {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetResponseHeaders sets the "response_headers" field.
func (_u *IdempotencyKeyUpdate) SetResponseHeaders(v map[string]string) *IdempotencyKeyUpdate {
	_u.mutation.SetResponseHeaders(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *IdempotencyKeyUpdate) SetExpiresAt(v time.Time) *IdempotencyKeyUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *IdempotencyKeyUpdate) SetNillableExpiresAt(v *time.Time) *IdempotencyKeyUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the IdempotencyKeyMutation object of the builder.
func (_u *IdempotencyKeyUpdate) Mutation() *IdempotencyKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IdempotencyKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IdempotencyKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IdempotencyKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IdempotencyKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IdempotencyKeyUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := idempotencykey.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "IdempotencyKey.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentID(); ok {
		if err := idempotencykey.PaymentIDValidator(v); err != nil {
			return &ValidationError{Name: "payment_id", err: fmt.Errorf(`ent: validator failed for field "IdempotencyKey.payment_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestHash(); ok {
		if err := idempotencykey.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "IdempotencyKey.request_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *IdempotencyKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(idempotencykey.Table, idempotencykey.Columns, sqlgraph.NewFieldSpec(idempotencykey.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(idempotencykey.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentID(); ok {
		_spec.SetField(idempotencykey.FieldPaymentID, field.TypeString, value)
	}
	if _u.mutation.PaymentIDCleared() {
		_spec.ClearField(idempotencykey.FieldPaymentID, field.TypeString)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(idempotencykey.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(idempotencykey.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequestHash(); ok {
		_spec.SetField(idempotencykey.FieldRequestHash, field.TypeString, value)
	}
	if _u.mutation.RequestHashCleared() {
		_spec.ClearField(idempotencykey.FieldRequestHash, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(idempotencykey.FieldResponseBody, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ResponseHeaders(); ok {
		_spec.SetField(idempotencykey.FieldResponseHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(idempotencykey.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idempotencykey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IdempotencyKeyUpdateOne is the builder for updating a single IdempotencyKey entity.
type IdempotencyKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IdempotencyKeyMutation
}

// SetKey sets the "key" field.
func (_u *IdempotencyKeyUpdateOne) SetKey(v string) *IdempotencyKeyUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *IdempotencyKeyUpdateOne) SetNillableKey(v *string) *IdempotencyKeyUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetPaymentID sets the "payment_id" field.
func (_u *IdempotencyKeyUpdateOne) SetPaymentID(v string) *IdempotencyKeyUpdateOne {
	_u.mutation.SetPaymentID(v)
	return _u
}

// SetNillablePaymentID sets the "payment_id" field if the given value is not nil.
func (_u *IdempotencyKeyUpdateOne) SetNillablePaymentID(v *string) *IdempotencyKeyUpdateOne {
	if v != nil {
		_u.SetPaymentID(*v)
	}
	return _u
}

// ClearPaymentID clears the value of the "payment_id" field.
func (_u *IdempotencyKeyUpdateOne) ClearPaymentID() *IdempotencyKeyUpdateOne {
	_u.mutation.ClearPaymentID()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *IdempotencyKeyUpdateOne) SetStatusCode(v int) *IdempotencyKeyUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *IdempotencyKeyUpdateOne) SetNillableStatusCode(v *int) *IdempotencyKeyUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *IdempotencyKeyUpdateOne) AddStatusCode(v int) *IdempotencyKeyUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetRequestHash sets the "request_hash" field.
func (_u *IdempotencyKeyUpdateOne) SetRequestHash(v string) *IdempotencyKeyUpdateOne {
	_u.mutation.SetRequestHash(v)
	return _u
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (_u *IdempotencyKeyUpdateOne) SetNillableRequestHash(v *string) *IdempotencyKeyUpdateOne {
	if v != nil {
		_u.SetRequestHash(*v)
	}
	return _u
}

// ClearRequestHash clears the value of the "request_hash" field.
func (_u *IdempotencyKeyUpdateOne) ClearRequestHash() *IdempotencyKeyUpdateOne {
	_u.mutation.ClearRequestHash()
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *IdempotencyKeyUpdateOne) SetResponseBody(v []byte) *IdempotencyKeyUpdateOne {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetResponseHeaders sets the "response_headers" field.
func (_u *IdempotencyKeyUpdateOne) SetResponseHeaders(v map[string]string) *IdempotencyKeyUpdateOne {
	_u.mutation.SetResponseHeaders(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *IdempotencyKeyUpdateOne) SetExpiresAt(v time.Time) *IdempotencyKeyUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *IdempotencyKeyUpdateOne) SetNillableExpiresAt(v *time.Time) *IdempotencyKeyUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the IdempotencyKeyMutation object of the builder.
func (_u *IdempotencyKeyUpdateOne) Mutation() *IdempotencyKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the IdempotencyKeyUpdate builder.
func (_u *IdempotencyKeyUpdateOne) Where(ps ...predicate.IdempotencyKey) *IdempotencyKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IdempotencyKeyUpdateOne) Select(field string, fields ...string) *IdempotencyKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IdempotencyKey entity.
func (_u *IdempotencyKeyUpdateOne) Save(ctx context.Context) (*IdempotencyKey, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IdempotencyKeyUpdateOne) SaveX(ctx context.Context) *IdempotencyKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IdempotencyKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IdempotencyKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IdempotencyKeyUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := idempotencykey.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "IdempotencyKey.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentID(); ok {
		if err := idempotencykey.PaymentIDValidator(v); err != nil {
			return &ValidationError{Name: "payment_id", err: fmt.Errorf(`ent: validator failed for field "IdempotencyKey.payment_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestHash(); ok {
		if err := idempotencykey.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "IdempotencyKey.request_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *IdempotencyKeyUpdateOne) sqlSave(ctx context.Context) (_node *IdempotencyKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(idempotencykey.Table, idempotencykey.Columns, sqlgraph.NewFieldSpec(idempotencykey.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IdempotencyKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, idempotencykey.FieldID)
		for _, f := range fields {
			if !idempotencykey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != idempotencykey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(idempotencykey.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentID(); ok {
		_spec.SetField(idempotencykey.FieldPaymentID, field.TypeString, value)
	}
	if _u.mutation.PaymentIDCleared() {
		_spec.ClearField(idempotencykey.FieldPaymentID, field.TypeString)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(idempotencykey.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(idempotencykey.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequestHash(); ok {
		_spec.SetField(idempotencykey.FieldRequestHash, field.TypeString, value)
	}
	if _u.mutation.RequestHashCleared() {
		_spec.ClearField(idempotencykey.FieldRequestHash, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(idempotencykey.FieldResponseBody, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ResponseHeaders(); ok {
		_spec.SetField(idempotencykey.FieldResponseHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(idempotencykey.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &IdempotencyKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idempotencykey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
