// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/devgugga/galaxy-pay/ent/idempotencykey"
	"github.com/google/uuid"
)

// IdempotencyKeyCreate is the builder for creating a IdempotencyKey entity.
type IdempotencyKeyCreate struct {
	config
	mutation *IdempotencyKeyMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *IdempotencyKeyCreate) SetKey(v string) *IdempotencyKeyCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetPaymentID sets the "payment_id" field.
func (_c *IdempotencyKeyCreate) SetPaymentID(v string) *IdempotencyKeyCreate {
	_c.mutation.SetPaymentID(v)
	return _c
}

// SetNillablePaymentID sets the "payment_id" field if the given value is not nil.
func (_c *IdempotencyKeyCreate) SetNillablePaymentID(v *string) *IdempotencyKeyCreate {
	if v != nil {
		_c.SetPaymentID(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *IdempotencyKeyCreate) SetStatusCode(v int) *IdempotencyKeyCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *IdempotencyKeyCreate) SetNillableStatusCode(v *int) *IdempotencyKeyCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetRequestHash sets the "request_hash" field.
func (_c *IdempotencyKeyCreate) SetRequestHash(v string) *IdempotencyKeyCreate {
	_c.mutation.SetRequestHash(v)
	return _c
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (_c *IdempotencyKeyCreate) SetNillableRequestHash(v *string) *IdempotencyKeyCreate {
	if v != nil {
		_c.SetRequestHash(*v)
	}
	return _c
}

// SetResponseBody sets the "response_body" field.
func (_c *IdempotencyKeyCreate) SetResponseBody(v []byte) *IdempotencyKeyCreate {
	_c.mutation.SetResponseBody(v)
	return _c
}

// SetResponseHeaders sets the "response_headers" field.
func (_c *IdempotencyKeyCreate) SetResponseHeaders(v map[string]string) *IdempotencyKeyCreate {
	_c.mutation.SetResponseHeaders(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *IdempotencyKeyCreate) SetCreatedAt(v time.Time) *IdempotencyKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IdempotencyKeyCreate) SetNillableCreatedAt(v *time.Time) *IdempotencyKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *IdempotencyKeyCreate) SetExpiresAt(v time.Time) *IdempotencyKeyCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *IdempotencyKeyCreate) SetID(v uuid.UUID) *IdempotencyKeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *IdempotencyKeyCreate) SetNillableID(v *uuid.UUID) *IdempotencyKeyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the IdempotencyKeyMutation object of the builder.
func (_c *IdempotencyKeyCreate) Mutation() *IdempotencyKeyMutation {
	return _c.mutation
}

// Save creates the IdempotencyKey in the database.
func (_c *IdempotencyKeyCreate) Save(ctx context.Context) (*IdempotencyKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IdempotencyKeyCreate) SaveX(ctx context.Context) *IdempotencyKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdempotencyKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdempotencyKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IdempotencyKeyCreate) defaults() {
	if _, ok := _c.mutation.StatusCode(); !ok {
		v := idempotencykey.DefaultStatusCode
		_c.mutation.SetStatusCode(v)
	}
	if _, ok := _c.mutation.ResponseHeaders(); !ok {
		v := idempotencykey.DefaultResponseHeaders
		_c.mutation.SetResponseHeaders(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := idempotencykey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := idempotencykey.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IdempotencyKeyCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "IdempotencyKey.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := idempotencykey.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "IdempotencyKey.key": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PaymentID(); ok {
		if err := idempotencykey.PaymentIDValidator(v); err != nil {
			return &ValidationError{Name: "payment_id", err: fmt.Errorf(`ent: validator failed for field "IdempotencyKey.payment_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "IdempotencyKey.status_code"`)}
	}
	if v, ok := _c.mutation.RequestHash(); ok {
		if err := idempotencykey.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "IdempotencyKey.request_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResponseBody(); !ok {
		return &ValidationError{Name: "response_body", err: errors.New(`ent: missing required field "IdempotencyKey.response_body"`)}
	}
	if _, ok := _c.mutation.ResponseHeaders(); !ok {
		return &ValidationError{Name: "response_headers", err: errors.New(`ent: missing required field "IdempotencyKey.response_headers"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IdempotencyKey.created_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "IdempotencyKey.expires_at"`)}
	}
	return nil
}

func (_c *IdempotencyKeyCreate) sqlSave(ctx context.Context) (*IdempotencyKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IdempotencyKeyCreate) createSpec() (*IdempotencyKey, *sqlgraph.CreateSpec) {
	var (
		_node = &IdempotencyKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(idempotencykey.Table, sqlgraph.NewFieldSpec(idempotencykey.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(idempotencykey.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.PaymentID(); ok {
		_spec.SetField(idempotencykey.FieldPaymentID, field.TypeString, value)
		_node.PaymentID = &value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(idempotencykey.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = value
	}
	if value, ok := _c.mutation.RequestHash(); ok {
		_spec.SetField(idempotencykey.FieldRequestHash, field.TypeString, value)
		_node.RequestHash = value
	}
	if value, ok := _c.mutation.ResponseBody(); ok {
		_spec.SetField(idempotencykey.FieldResponseBody, field.TypeBytes, value)
		_node.ResponseBody = value
	}
	if value, ok := _c.mutation.ResponseHeaders(); ok {
		_spec.SetField(idempotencykey.FieldResponseHeaders, field.TypeJSON, value)
		_node.ResponseHeaders = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(idempotencykey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(idempotencykey.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// IdempotencyKeyCreateBulk is the builder for creating many IdempotencyKey entities in bulk.
type IdempotencyKeyCreateBulk struct {
	config
	err      error
	builders []*IdempotencyKeyCreate
}

// Save creates the IdempotencyKey entities in the database.
func (_c *IdempotencyKeyCreateBulk) Save(ctx context.Context) ([]*IdempotencyKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IdempotencyKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IdempotencyKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IdempotencyKeyCreateBulk) SaveX(ctx context.Context) []*IdempotencyKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdempotencyKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdempotencyKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
