// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/devgugga/galaxy-pay/ent/idempotencykey"
	"github.com/google/uuid"
)

// IdempotencyKey is the model entity for the IdempotencyKey schema.
type IdempotencyKey struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Idempotency key from client (UUID)
	Key string `json:"key,omitempty"`
	// ID of the payment created (if applicable)
	PaymentID *string `json:"payment_id,omitempty"`
	// HTTP status code of the response
	StatusCode int `json:"status_code,omitempty"`
	// Hash of the request body for validation
	RequestHash string `json:"request_hash,omitempty"`
	// Serialized response body
	ResponseBody []byte `json:"response_body,omitempty"`
	// Response headers as JSON
	ResponseHeaders map[string]string `json:"response_headers,omitempty"`
	// Timestamp when the key was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Timestamp when the key expires
	ExpiresAt    time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IdempotencyKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case idempotencykey.FieldResponseBody, idempotencykey.FieldResponseHeaders:
			values[i] = new([]byte)
		case idempotencykey.FieldStatusCode:
			values[i] = new(sql.NullInt64)
		case idempotencykey.FieldKey, idempotencykey.FieldPaymentID, idempotencykey.FieldRequestHash:
			values[i] = new(sql.NullString)
		case idempotencykey.FieldCreatedAt, idempotencykey.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case idempotencykey.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IdempotencyKey fields.
func (_m *IdempotencyKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case idempotencykey.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case idempotencykey.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case idempotencykey.FieldPaymentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_id", values[i])
			} else if value.Valid {
				_m.PaymentID = new(string)
				*_m.PaymentID = value.String
			}
		case idempotencykey.FieldStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_code", values[i])
			} else if value.Valid {
				_m.StatusCode = int(value.Int64)
			}
		case idempotencykey.FieldRequestHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_hash", values[i])
			} else if value.Valid {
				_m.RequestHash = value.String
			}
		case idempotencykey.FieldResponseBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_body", values[i])
			} else if value != nil {
				_m.ResponseBody = *value
			}
		case idempotencykey.FieldResponseHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResponseHeaders); err != nil {
					return fmt.Errorf("unmarshal field response_headers: %w", err)
				}
			}
		case idempotencykey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case idempotencykey.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IdempotencyKey.
// This includes values selected through modifiers, order, etc.
func (_m *IdempotencyKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IdempotencyKey.
// Note that you need to call IdempotencyKey.Unwrap() before calling this method if this IdempotencyKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IdempotencyKey) Update() *IdempotencyKeyUpdateOne {
	return NewIdempotencyKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IdempotencyKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IdempotencyKey) Unwrap() *IdempotencyKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IdempotencyKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IdempotencyKey) String() string {
	var builder strings.Builder
	builder.WriteString("IdempotencyKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	if v := _m.PaymentID; v != nil {
		builder.WriteString("payment_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.StatusCode))
	builder.WriteString(", ")
	builder.WriteString("request_hash=")
	builder.WriteString(_m.RequestHash)
	builder.WriteString(", ")
	builder.WriteString("response_body=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseBody))
	builder.WriteString(", ")
	builder.WriteString("response_headers=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseHeaders))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// IdempotencyKeys is a parsable slice of IdempotencyKey.
type IdempotencyKeys []*IdempotencyKey
