// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/devgugga/galaxy-pay/ent/idempotencykey"
	"github.com/devgugga/galaxy-pay/ent/predicate"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeIdempotencyKey = "IdempotencyKey"
)

// IdempotencyKeyMutation represents an operation that mutates the IdempotencyKey nodes in the graph.
type IdempotencyKeyMutation struct {
	config
	op               Op
	typ              string
	id               *uuid.UUID
	key              *string
	payment_id       *string
	status_code      *int
	addstatus_code   *int
	request_hash     *string
	response_body    *[]byte
	response_headers *map[string]string
	created_at       *time.Time
	expires_at       *time.Time
	clearedFields    map[string]struct{}
	done             bool
	oldValue         func(context.Context) (*IdempotencyKey, error)
	predicates       []predicate.IdempotencyKey
}

var _ ent.Mutation = (*IdempotencyKeyMutation)(nil)

// idempotencykeyOption allows management of the mutation configuration using functional options.
type idempotencykeyOption func(*IdempotencyKeyMutation)

// newIdempotencyKeyMutation creates new mutation for the IdempotencyKey entity.
func newIdempotencyKeyMutation(c config, op Op, opts ...idempotencykeyOption) *IdempotencyKeyMutation {
	m := &IdempotencyKeyMutation{
		config:        c,
		op:            op,
		typ:           TypeIdempotencyKey,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withIdempotencyKeyID sets the ID field of the mutation.
func withIdempotencyKeyID(id uuid.UUID) idempotencykeyOption {
	return func(m *IdempotencyKeyMutation) {
		var (
			err   error
			once  sync.Once
			value *IdempotencyKey
		)
		m.oldValue = func(ctx context.Context) (*IdempotencyKey, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().IdempotencyKey.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withIdempotencyKey sets the old IdempotencyKey of the mutation.
func withIdempotencyKey(node *IdempotencyKey) idempotencykeyOption {
	return func(m *IdempotencyKeyMutation) {
		m.oldValue = func(context.Context) (*IdempotencyKey, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m IdempotencyKeyMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m IdempotencyKeyMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of IdempotencyKey entities.
func (m *IdempotencyKeyMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *IdempotencyKeyMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *IdempotencyKeyMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().IdempotencyKey.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetKey sets the "key" field.
func (m *IdempotencyKeyMutation) SetKey(s string) {
	m.key = &s
}

// Key returns the value of the "key" field in the mutation.
func (m *IdempotencyKeyMutation) Key() (r string, exists bool) {
	v := m.key
	if v == nil {
		return
	}
	return *v, true
}

// OldKey returns the old "key" field's value of the IdempotencyKey entity.
// If the IdempotencyKey object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *IdempotencyKeyMutation) OldKey(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldKey: %w", err)
	}
	return oldValue.Key, nil
}

// ResetKey resets all changes to the "key" field.
func (m *IdempotencyKeyMutation) ResetKey() {
	m.key = nil
}

// SetPaymentID sets the "payment_id" field.
func (m *IdempotencyKeyMutation) SetPaymentID(s string) {
	m.payment_id = &s
}

// PaymentID returns the value of the "payment_id" field in the mutation.
func (m *IdempotencyKeyMutation) PaymentID() (r string, exists bool) {
	v := m.payment_id
	if v == nil {
		return
	}
	return *v, true
}

// OldPaymentID returns the old "payment_id" field's value of the IdempotencyKey entity.
// If the IdempotencyKey object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *IdempotencyKeyMutation) OldPaymentID(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPaymentID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPaymentID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPaymentID: %w", err)
	}
	return oldValue.PaymentID, nil
}

// ClearPaymentID clears the value of the "payment_id" field.
func (m *IdempotencyKeyMutation) ClearPaymentID() {
	m.payment_id = nil
	m.clearedFields[idempotencykey.FieldPaymentID] = struct{}{}
}

// PaymentIDCleared returns if the "payment_id" field was cleared in this mutation.
func (m *IdempotencyKeyMutation) PaymentIDCleared() bool {
	_, ok := m.clearedFields[idempotencykey.FieldPaymentID]
	return ok
}

// ResetPaymentID resets all changes to the "payment_id" field.
func (m *IdempotencyKeyMutation) ResetPaymentID() {
	m.payment_id = nil
	delete(m.clearedFields, idempotencykey.FieldPaymentID)
}

// SetStatusCode sets the "status_code" field.
func (m *IdempotencyKeyMutation) SetStatusCode(i int) {
	m.status_code = &i
	m.addstatus_code = nil
}

// StatusCode returns the value of the "status_code" field in the mutation.
func (m *IdempotencyKeyMutation) StatusCode() (r int, exists bool) {
	v := m.status_code
	if v == nil {
		return
	}
	return *v, true
}

// OldStatusCode returns the old "status_code" field's value of the IdempotencyKey entity.
// If the IdempotencyKey object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *IdempotencyKeyMutation) OldStatusCode(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatusCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatusCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatusCode: %w", err)
	}
	return oldValue.StatusCode, nil
}

// AddStatusCode adds i to the "status_code" field.
func (m *IdempotencyKeyMutation) AddStatusCode(i int) {
	if m.addstatus_code != nil {
		*m.addstatus_code += i
	} else {
		m.addstatus_code = &i
	}
}

// AddedStatusCode returns the value that was added to the "status_code" field in this mutation.
func (m *IdempotencyKeyMutation) AddedStatusCode() (r int, exists bool) {
	v := m.addstatus_code
	if v == nil {
		return
	}
	return *v, true
}

// ResetStatusCode resets all changes to the "status_code" field.
func (m *IdempotencyKeyMutation) ResetStatusCode() {
	m.status_code = nil
	m.addstatus_code = nil
}

// SetRequestHash sets the "request_hash" field.
func (m *IdempotencyKeyMutation) SetRequestHash(s string) {
	m.request_hash = &s
}

// RequestHash returns the value of the "request_hash" field in the mutation.
func (m *IdempotencyKeyMutation) RequestHash() (r string, exists bool) {
	v := m.request_hash
	if v == nil {
		return
	}
	return *v, true
}

// OldRequestHash returns the old "request_hash" field's value of the IdempotencyKey entity.
// If the IdempotencyKey object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *IdempotencyKeyMutation) OldRequestHash(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRequestHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRequestHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRequestHash: %w", err)
	}
	return oldValue.RequestHash, nil
}

// ClearRequestHash clears the value of the "request_hash" field.
func (m *IdempotencyKeyMutation) ClearRequestHash() {
	m.request_hash = nil
	m.clearedFields[idempotencykey.FieldRequestHash] = struct{}{}
}

// RequestHashCleared returns if the "request_hash" field was cleared in this mutation.
func (m *IdempotencyKeyMutation) RequestHashCleared() bool {
	_, ok := m.clearedFields[idempotencykey.FieldRequestHash]
	return ok
}

// ResetRequestHash resets all changes to the "request_hash" field.
func (m *IdempotencyKeyMutation) ResetRequestHash() {
	m.request_hash = nil
	delete(m.clearedFields, idempotencykey.FieldRequestHash)
}

// SetResponseBody sets the "response_body" field.
func (m *IdempotencyKeyMutation) SetResponseBody(b []byte) {
	m.response_body = &b
}

// ResponseBody returns the value of the "response_body" field in the mutation.
func (m *IdempotencyKeyMutation) ResponseBody() (r []byte, exists bool) {
	v := m.response_body
	if v == nil {
		return
	}
	return *v, true
}

// OldResponseBody returns the old "response_body" field's value of the IdempotencyKey entity.
// If the IdempotencyKey object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *IdempotencyKeyMutation) OldResponseBody(ctx context.Context) (v []byte, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResponseBody is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResponseBody requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResponseBody: %w", err)
	}
	return oldValue.ResponseBody, nil
}

// ResetResponseBody resets all changes to the "response_body" field.
func (m *IdempotencyKeyMutation) ResetResponseBody() {
	m.response_body = nil
}

// SetResponseHeaders sets the "response_headers" field.
func (m *IdempotencyKeyMutation) SetResponseHeaders(value map[string]string) {
	m.response_headers = &value
}

// ResponseHeaders returns the value of the "response_headers" field in the mutation.
func (m *IdempotencyKeyMutation) ResponseHeaders() (r map[string]string, exists bool) {
	v := m.response_headers
	if v == nil {
		return
	}
	return *v, true
}

// OldResponseHeaders returns the old "response_headers" field's value of the IdempotencyKey entity.
// If the IdempotencyKey object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *IdempotencyKeyMutation) OldResponseHeaders(ctx context.Context) (v map[string]string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResponseHeaders is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResponseHeaders requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResponseHeaders: %w", err)
	}
	return oldValue.ResponseHeaders, nil
}

// ResetResponseHeaders resets all changes to the "response_headers" field.
func (m *IdempotencyKeyMutation) ResetResponseHeaders() {
	m.response_headers = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *IdempotencyKeyMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *IdempotencyKeyMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the IdempotencyKey entity.
// If the IdempotencyKey object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *IdempotencyKeyMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *IdempotencyKeyMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetExpiresAt sets the "expires_at" field.
func (m *IdempotencyKeyMutation) SetExpiresAt(t time.Time) {
	m.expires_at = &t
}

// ExpiresAt returns the value of the "expires_at" field in the mutation.
func (m *IdempotencyKeyMutation) ExpiresAt() (r time.Time, exists bool) {
	v := m.expires_at
	if v == nil {
		return
	}
	return *v, true
}

// OldExpiresAt returns the old "expires_at" field's value of the IdempotencyKey entity.
// If the IdempotencyKey object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *IdempotencyKeyMutation) OldExpiresAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpiresAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpiresAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpiresAt: %w", err)
	}
	return oldValue.ExpiresAt, nil
}

// ResetExpiresAt resets all changes to the "expires_at" field.
func (m *IdempotencyKeyMutation) ResetExpiresAt() {
	m.expires_at = nil
}

// Where appends a list predicates to the IdempotencyKeyMutation builder.
func (m *IdempotencyKeyMutation) Where(ps ...predicate.IdempotencyKey) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the IdempotencyKeyMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *IdempotencyKeyMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.IdempotencyKey, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *IdempotencyKeyMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *IdempotencyKeyMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (IdempotencyKey).
func (m *IdempotencyKeyMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *IdempotencyKeyMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.key != nil {
		fields = append(fields, idempotencykey.FieldKey)
	}
	if m.payment_id != nil {
		fields = append(fields, idempotencykey.FieldPaymentID)
	}
	if m.status_code != nil {
		fields = append(fields, idempotencykey.FieldStatusCode)
	}
	if m.request_hash != nil {
		fields = append(fields, idempotencykey.FieldRequestHash)
	}
	if m.response_body != nil {
		fields = append(fields, idempotencykey.FieldResponseBody)
	}
	if m.response_headers != nil {
		fields = append(fields, idempotencykey.FieldResponseHeaders)
	}
	if m.created_at != nil {
		fields = append(fields, idempotencykey.FieldCreatedAt)
	}
	if m.expires_at != nil {
		fields = append(fields, idempotencykey.FieldExpiresAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *IdempotencyKeyMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case idempotencykey.FieldKey:
		return m.Key()
	case idempotencykey.FieldPaymentID:
		return m.PaymentID()
	case idempotencykey.FieldStatusCode:
		return m.StatusCode()
	case idempotencykey.FieldRequestHash:
		return m.RequestHash()
	case idempotencykey.FieldResponseBody:
		return m.ResponseBody()
	case idempotencykey.FieldResponseHeaders:
		return m.ResponseHeaders()
	case idempotencykey.FieldCreatedAt:
		return m.CreatedAt()
	case idempotencykey.FieldExpiresAt:
		return m.ExpiresAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *IdempotencyKeyMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case idempotencykey.FieldKey:
		return m.OldKey(ctx)
	case idempotencykey.FieldPaymentID:
		return m.OldPaymentID(ctx)
	case idempotencykey.FieldStatusCode:
		return m.OldStatusCode(ctx)
	case idempotencykey.FieldRequestHash:
		return m.OldRequestHash(ctx)
	case idempotencykey.FieldResponseBody:
		return m.OldResponseBody(ctx)
	case idempotencykey.FieldResponseHeaders:
		return m.OldResponseHeaders(ctx)
	case idempotencykey.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case idempotencykey.FieldExpiresAt:
		return m.OldExpiresAt(ctx)
	}
	return nil, fmt.Errorf("unknown IdempotencyKey field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *IdempotencyKeyMutation) SetField(name string, value ent.Value) error {
	switch name {
	case idempotencykey.FieldKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKey(v)
		return nil
	case idempotencykey.FieldPaymentID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPaymentID(v)
		return nil
	case idempotencykey.FieldStatusCode:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatusCode(v)
		return nil
	case idempotencykey.FieldRequestHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRequestHash(v)
		return nil
	case idempotencykey.FieldResponseBody:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResponseBody(v)
		return nil
	case idempotencykey.FieldResponseHeaders:
		v, ok := value.(map[string]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResponseHeaders(v)
		return nil
	case idempotencykey.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case idempotencykey.FieldExpiresAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpiresAt(v)
		return nil
	}
	return fmt.Errorf("unknown IdempotencyKey field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *IdempotencyKeyMutation) AddedFields() []string {
	var fields []string
	if m.addstatus_code != nil {
		fields = append(fields, idempotencykey.FieldStatusCode)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *IdempotencyKeyMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case idempotencykey.FieldStatusCode:
		return m.AddedStatusCode()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *IdempotencyKeyMutation) AddField(name string, value ent.Value) error {
	switch name {
	case idempotencykey.FieldStatusCode:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStatusCode(v)
		return nil
	}
	return fmt.Errorf("unknown IdempotencyKey numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *IdempotencyKeyMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(idempotencykey.FieldPaymentID) {
		fields = append(fields, idempotencykey.FieldPaymentID)
	}
	if m.FieldCleared(idempotencykey.FieldRequestHash) {
		fields = append(fields, idempotencykey.FieldRequestHash)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *IdempotencyKeyMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *IdempotencyKeyMutation) ClearField(name string) error {
	switch name {
	case idempotencykey.FieldPaymentID:
		m.ClearPaymentID()
		return nil
	case idempotencykey.FieldRequestHash:
		m.ClearRequestHash()
		return nil
	}
	return fmt.Errorf("unknown IdempotencyKey nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *IdempotencyKeyMutation) ResetField(name string) error {
	switch name {
	case idempotencykey.FieldKey:
		m.ResetKey()
		return nil
	case idempotencykey.FieldPaymentID:
		m.ResetPaymentID()
		return nil
	case idempotencykey.FieldStatusCode:
		m.ResetStatusCode()
		return nil
	case idempotencykey.FieldRequestHash:
		m.ResetRequestHash()
		return nil
	case idempotencykey.FieldResponseBody:
		m.ResetResponseBody()
		return nil
	case idempotencykey.FieldResponseHeaders:
		m.ResetResponseHeaders()
		return nil
	case idempotencykey.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case idempotencykey.FieldExpiresAt:
		m.ResetExpiresAt()
		return nil
	}
	return fmt.Errorf("unknown IdempotencyKey field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *IdempotencyKeyMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *IdempotencyKeyMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *IdempotencyKeyMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *IdempotencyKeyMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *IdempotencyKeyMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *IdempotencyKeyMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *IdempotencyKeyMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown IdempotencyKey unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *IdempotencyKeyMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown IdempotencyKey edge %s", name)
}
