// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/devgugga/galaxy-pay/ent/idempotencykey"
	"github.com/devgugga/galaxy-pay/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	idempotencykeyFields := schema.IdempotencyKey{}.Fields()
	_ = idempotencykeyFields
	// idempotencykeyDescKey is the schema descriptor for key field.
	idempotencykeyDescKey := idempotencykeyFields[1].Descriptor()
	// idempotencykey.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	idempotencykey.KeyValidator = func() func(string) error {
		validators := idempotencykeyDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// idempotencykeyDescPaymentID is the schema descriptor for payment_id field.
	idempotencykeyDescPaymentID := idempotencykeyFields[2].Descriptor()
	// idempotencykey.PaymentIDValidator is a validator for the "payment_id" field. It is called by the builders before save.
	idempotencykey.PaymentIDValidator = idempotencykeyDescPaymentID.Validators[0].(func(string) error)
	// idempotencykeyDescStatusCode is the schema descriptor for status_code field.
	idempotencykeyDescStatusCode := idempotencykeyFields[3].Descriptor()
	// idempotencykey.DefaultStatusCode holds the default value on creation for the status_code field.
	idempotencykey.DefaultStatusCode = idempotencykeyDescStatusCode.Default.(int)
	// idempotencykeyDescRequestHash is the schema descriptor for request_hash field.
	idempotencykeyDescRequestHash := idempotencykeyFields[4].Descriptor()
	// idempotencykey.RequestHashValidator is a validator for the "request_hash" field. It is called by the builders before save.
	idempotencykey.RequestHashValidator = idempotencykeyDescRequestHash.Validators[0].(func(string) error)
	// idempotencykeyDescResponseHeaders is the schema descriptor for response_headers field.
	idempotencykeyDescResponseHeaders := idempotencykeyFields[6].Descriptor()
	// idempotencykey.DefaultResponseHeaders holds the default value on creation for the response_headers field.
	idempotencykey.DefaultResponseHeaders = idempotencykeyDescResponseHeaders.Default.(map[string]string)
	// idempotencykeyDescCreatedAt is the schema descriptor for created_at field.
	idempotencykeyDescCreatedAt := idempotencykeyFields[7].Descriptor()
	// idempotencykey.DefaultCreatedAt holds the default value on creation for the created_at field.
	idempotencykey.DefaultCreatedAt = idempotencykeyDescCreatedAt.Default.(func() time.Time)
	// idempotencykeyDescID is the schema descriptor for id field.
	idempotencykeyDescID := idempotencykeyFields[0].Descriptor()
	// idempotencykey.DefaultID holds the default value on creation for the id field.
	idempotencykey.DefaultID = idempotencykeyDescID.Default.(func() uuid.UUID)
}
