// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// IdempotencyKey is the predicate function for idempotencykey builders.
type IdempotencyKey func(*sql.Selector)
